### ISSUE TITLE
Incorrect base URL usage.

### ISSUE THREAD

**Issue by tcpdump9** [svyatoslav-kubakh/postfix-admin#3]
I have experienced an issue with base_url configuration.
When I tried to use /admin for login page I get URl admin/admin/site/login. When I logged in - pressing any button gives the same effect - additional /admin section automatically added to my webpage URL. Can you explain base_url setting with an example or help me to fix this someway?

**Comment by svyatoslav-kubakh** [comment]
@tcpdump9 to fix bug you reported, simply add empty environment setting ([.env](https://github.com/svyatoslav-kubakh/postfix-admin/blob/master/.env.dist))
> BASE_URL =

The fixes were commited (d21255309460d381d2a1087b9465f74f106efbf8) and will soon be added as part of the release [1.1.0](https://github.com/svyatoslav-kubakh/postfix-admin/releases/tag/1.1.0)

**Comment by svyatoslav-kubakh** [comment]
Released:  #5
